version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    working_directory: ~/repo
    shell: /bin/sh -leo pipefail
    environment:
       - BASH_ENV: /etc/profile
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup Environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=jmercha/web' >> $BASH_ENV 
      - run:
          name: Setup Docker
          command: apk add docker curl bash
      - run:
          name: Docker push
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build -t $IMAGE_NAME:latest .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$TAG
      - run:
          name: Install kubectl
          command: |
            if [ ! -f "./kubectl" ]; then
              curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
              chmod u+x ./kubectl
            fi
      - deploy: 
          command: ./deploy.sh
